#!/bin/bash

# Assurer que le script d2 a les permissions d'exécution
chmod 777 traitement/d2

# Définition de la fonction d2
d2(){

	# Enregistrez le temps de début.
        debut_timer_d2=$(date +%s)

# Trouver les conducteurs avec la plus grande distance
	cut -d';' -f5,6 data/data.csv |
	awk -v OFS=';' -F';'  'NR>1 {journey_lengths_sum[$2]+=$1} END {for (driver in journey_lengths_sum) print driver, journey_lengths_sum[driver]}' |
	sort -t';' -nrk2,2 |
	head -n10 |
	awk -F';' '{gsub(/ /, ",", $2); print $2 ";" $1}' > temp/temp_d2.csv

#Afficher les résultats
	cat temp/temp_d2.csv

fin_timer_d2=$(date +%s)

        # Calculez la durée totale en secondes.
        duree_option_d2=$((fin_timer_d2 - debut_timer_d2))

        # Affichez la durée.
        echo  "Le traitement de l'option -d2 a pris $duree_option_d2 secondes."
	
    # Créer un fichier de données pour l'histogramme
     awk -F';' '{print $2 "," $1}' temp/temp_d2.csv | sort -t',' -k2,2n > temp/histogram_datad2.csv

 # Appel de la fonction pour tracer le graphique
    generate_d2

	 # Ouvre automatiquement l'image du graphique
        display images/graphique_d2.png


}

generate_d2() {
    # Vérification si le fichier existe
if [ ! -f "temp/histogram_datad2.csv" ]; then
    echo "Le fichier 'temp/histogram_datad2.csv' n'existe pas."
    exit 1
fi

        # Exécution de Gnuplot
        gnuplot <<- GNUPLOT_SCRIPT
	#Définition du séparateur
        set datafile separator ","
	#Définition de la taille de l'image :
        set terminal pngcairo 
	#Sauvegarde du graphique dans le fichier images :
        set output 'images/graphique_d2.png'

        set style fill solid  # solid color boxes
        unset key             # turn off all titles

        set boxwidth 0.5
        set offsets 0,0,0.5-0.5/2,0.5
        set xrange [0:*]
	set yrange [0:*]  # Utilisez la plage par défaut pour l'axe y
	set title 'Graphique -d2'
        set ylabel 'Noms des conducteurs'
        set xlabel 'Distance parcourue'
	set xtics rotate by -45


        plot 'temp/histogram_datad2.csv' using (0.5*column(2)):0:(0.5*column(2)):(0.5/2.):(column(0)+1):ytic(1) with boxxy lc var
GNUPLOT_SCRIPT

}
# Appel de la fonction d2
d2
