#!/bin/bash

chmod 777 traitement/t
chmod 777 progc/t.c

# Définition de la fonction t
t() {


    # Compiler t.c pour créer un exécutable
    gcc -o progc/t progc/t.c

# Vérifier si l'exécutable existe et est exécutable
if [[ ! -x "progc/t" ]]; then
    echo "L'exécutable $progc/t est introuvable ou n'est pas exécutable."
    exit 1
fi

    # Enregistrez le temps de début.
        debut_timer_t=$(date +%s)

        cat "data/data.csv" | tail +2 | cut -d';' -f1,2,3,4| ./progc/t | head -10 > temp/temp_t.csv

	cat "temp/temp_t.csv" | sort -t ';' -k1,1 -f > temp/histogram_datat.csv

fin_timer_t=$(date +%s)

        # Calculez la durée totale en secondes.
        duree_option_t=$((fin_timer_t - debut_timer_t))

        # Affichez la durée.
        echo  "Le traitement de l'option -t a pris $duree_option_t secondes."

    # Revenir au répertoire précédent si nécessaire
    cd .

        generate_t

display images/graphique_t.png

}

generate_t() {
    # Vérification si le fichier existe
    if [ ! -f "temp/histogram_datat.csv" ]; then
        echo "Le fichier 'temp/histogram_datat.csv' n'existe pas."
        exit 1
    fi

    # Partie graphique (gnuplot)
    gnuplot <<-GNUPLOT_SCRIPT

    # Ouverture du script Gnuplot
        set terminal png # Définit le type de fichier de sortie comme une image PNG
        set output 'images/graphique_t.png' # Définit le nom et l'emplacement du fichier de sortie
        set datafile separator ";"

        # Configuration du tracé
        set title "Graphique -t"
        set xlabel "Nom de la ville"
        set ylabel "Nombre de passage/depart"
        set boxwidth 0.9 relative
        set style data histograms
        set style fill solid
        set xtics rotate by -45
        set yrange [0:*]

        # Tracer les données à partir du fichier
        plot 'temp/histogram_datat.csv' using 2:xtic(1) title "Nombre de passage", \
     '' using 3 title "Nombre de depart"

GNUPLOT_SCRIPT
}

t
